name: Atualizar painel

on:
  schedule:
    - cron: "*/15 * * * *"  # a cada 15 minutos
  workflow_dispatch:

jobs:
  gerar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # <--- CRUCIAL: Baixa todo o histórico para o rebase funcionar

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Gerar index.html
        env:
          URL_API: ${{ secrets.URL_API }}
          API_KEY_N8N: ${{ secrets.API_KEY_N8N }}
          GITHUB_REPOSITORY: ${{ InovacaoMavel/Painel-Cron-n8n }}  # ex: "seu-usuario/seu-repo"
        run: python coleta_cron.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Define globalmente a estratégia de pull como rebase para evitar avisos do Git
          git config pull.rebase true
          
          git add index.html
          
          if ! git diff --staged --quiet; then
            git commit -m "chore: atualiza painel $(date +'%d/%m/%Y %H:%M')"
            
            # Puxa as alterações mais recentes logo antes de enviar
            git pull origin main
            
            git push origin main
          else
            echo "Nenhuma alteração detectada no index.html"
          fi
